### ISSUE TITLE
Shadow on rotation

### ISSUE THREAD

**Issue by x4080** [NathanWalker/MaterialCard#1]
Hi Nathan, I found that when device rotates, the shadow is not right (stick like before rotation)

**Comment by NathanWalker** [comment]
Thanks for the report. I'll take look when I can!

**Comment by x4080** [comment]
Hi Nathan, the bug I found was when using nativescript in gridlayout so that the card is centered using Brad Martin's cardview plugin, it could be because when device rotate, it is not call to refresh your MaterialCard

Is there any function to refresh when the NS layout changes? Is is calling materialize() will do the layout ?

Thanks

**Comment by x4080** [comment]
Just call materialize() solves it :)
